version: "3"

volumes:
  api:
  client:

services:
  client:
    environment:
      WATCHPACK_POLLING: "true"
    env_file:
      - ./client/.env
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client/:/app/
    container_name: frontend
    ports:
      - "5178:5178"

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - 3000:3000
    restart: always
    env_file:
      - ./api/.env
    volumes:
      - ./api/:/api/
